#!/usr/bin/env perl -w

use strict;

use Test::More tests => 58;
use Constants::Reports;

ok(defined Constants::Reports::CHANNEL, 'Channel report defined');
ok(defined Constants::Reports::MIN_REPORTS, 'Min reports defined');
ok(defined Constants::Reports::TRAFFIC, 'Traffic report defined');
ok(defined Constants::Reports::BROWSER, 'Browser report defined');
ok(defined Constants::Reports::COUNTRY, 'Country report defined');
ok(defined Constants::Reports::LANGUAGE, 'Language report defined');
ok(defined Constants::Reports::TIME_ZONE, 'Time zone report defined');
ok(defined Constants::Reports::COLOR_BITS, 'Color bits report defined');
ok(defined Constants::Reports::RESOLUTION, 'Resolution report defined');
ok(defined Constants::Reports::OP_SYS, 'Op sys report defined');
ok(defined Constants::Reports::HOST, 'Host report defined');
ok(defined Constants::Reports::REFERRER_PAGE, 'Referrer page report defined');
ok(defined Constants::Reports::REFERRER_SITE, 'Referrer site report defined');
ok(defined Constants::Reports::REFERRER_SEARCH, 'Referrer search report defined');
ok(defined Constants::Reports::SEARCH_WORD, 'Search word report defined');
ok(defined Constants::Reports::SEARCH_PHRASE, 'Search phrase report defined');
ok(defined Constants::Reports::PAGE, 'Page report defined');
ok(defined Constants::Reports::DIRECTORY, 'Directory report defined');
ok(defined Constants::Reports::ENTRY_PAGE, 'Entry page report defined');
ok(defined Constants::Reports::EXIT_PAGE, 'Exit page report defined');
ok(defined Constants::Reports::PAGE_NAVIGATION, 'Page navigation report defined');
ok(defined Constants::Reports::PAGE_VISITS, 'Page visits report defined');
ok(defined Constants::Reports::COMMERCE_REFERRER, 'Commerce referrer report defined');
ok(defined Constants::Reports::COMMERCE_ENTRY_PAGE, 'Commerce entry page report defined');
ok(defined Constants::Reports::PAGE_DURATION, 'Page duration report defined');
ok(defined Constants::Reports::HOUR_OF_DAY_VISITS, 'Hour of day visits report defined');
ok(defined Constants::Reports::COMMERCE_WORD, 'Commerce word report defined');
ok(defined Constants::Reports::COMMERCE_PHRASE, 'Commerce phrase report defined');
ok(defined Constants::Reports::BOUNCE_PAGE, 'Bounce page report defined');
ok(defined Constants::Reports::REFERRER_HITS, 'Referrer hits report defined');
ok(defined Constants::Reports::VISIT_DURATION, 'Visit duration report defined');
ok(defined Constants::Reports::VISIT_PAGES, 'Visit pages report defined');
ok(defined Constants::Reports::SEARCH_ENGINE_PHRASE, 'Search engine phrase report defined');
ok(defined Constants::Reports::COMMERCE_ENGINE_PHRASE, 'Commerce engine phrase report defined');
ok(defined Constants::Reports::MAIL, 'Mail report defined');
ok(defined Constants::Reports::HOUR_OF_DAY_HITS, 'Hour of day hits report defined');
ok(defined Constants::Reports::SPIDER, 'Spider report defined');
ok(defined Constants::Reports::REFERRER_PATH, 'Referrer path report defined');
ok(defined Constants::Reports::LOCATION, 'Location report defined');
ok(defined Constants::Reports::CAMPAIGN_ENTRY_PAGE, 'Campaign entry page report defined');
ok(defined Constants::Reports::CAMPAIGN_COMMERCE, 'Campaign commerce report defined');
ok(defined Constants::Reports::COMMERCE_PATH, 'Commerce path report defined');
ok(defined Constants::Reports::LINK, 'Link report defined');
ok(defined Constants::Reports::FILE, 'File report defined');
ok(defined Constants::Reports::JAVA_VERSION, 'Java version report defined');
ok(defined Constants::Reports::JAVASCRIPT_VERSION, 'Javascript version report defined');
ok(defined Constants::Reports::FLASH_VERSION, 'Flash version report defined');
ok(defined Constants::Reports::PAGE_LOAD_TIME, 'Page load time report defined');
ok(defined Constants::Reports::PAGE_CLASS, 'Page class report defined');
ok(defined Constants::Reports::CAMPAIGN, 'Campaign report defined');
ok(defined Constants::Reports::MAX_REPORTS, 'Max reports defined');
ok(defined Constants::Reports::FREQUENCY, 'Frequency report defined');
ok(defined Constants::Reports::RECENCY, 'Recency report defined');
ok(defined Constants::Reports::RANGE, 'Range report defined');
ok(defined Constants::Reports::USER, 'User report defined');
ok(defined Constants::Reports::THIS_VISIT_DURATION, 'This visit duration defined');
ok(defined Constants::Reports::THIS_VISIT_PAGES, 'This visit pages defined');
ok(defined Constants::Reports::THIS_VISIT_PATH, 'This visit path defined');
