browser:
    desc: update web page details for monitored sites
    when:
        hours: all
        mins: 0

monitor:
    desc: Run system monitors and report any problems via email
    when:
        hours: all
        mins: [0, 10, 20, 30, 40, 50]

rollover:
    desc: At the end of each month, rollover databases for high traffic sites
    when:
        hours: all
        mins: 0

fixer:
    desc: Find missing reports and fix them by generating them
    when:
        hours: 4
        mins: 30
    args:
        date: 2

anomolies:
    desc: Detect anomolies in the traffic levels for all web sites
    when:
        hours: 0
        mins: 5

purge:
    desc: Remove old files
    when:
        hours: 0
        mins: 15

repairman:
    desc: Repair MySQL tables that are waiting to be fixed
    when:
        hours: 0
        mins: 25
