default:
    driver: mysql
    host: ho2.legendum.net
    username: sitestats
    password: reborn15
    database: site
    auto_commit: true
    insert_delayed: false

de2.legendum.net:
    host: de2.legendum.net
