#!/usr/bin/env perl

=head1 NAME

Constants::Countries - Contains all country codes (2 letters) and full names

=head1 VERSION

This document refers to version 1.0 of Constants::Countries, released Jul 07, 2015

=head1 DESCRIPTION

Constants::Countries contains all country codes (2 letters) and full names.

=head2 Properties

=over 4

None

=back

=cut
package Constants::Countries;
$VERSION = "1.0";

use strict;

# Country codes and names

use constant NAMES => {
    aa => "Unknown",
    ad => "Andorra, Principality of",
    ae => "United Arab Emirates",
    af => "Afghanistan, Islamic State of",
    ag => "Antigua and Barbuda",
    ai => "Anguilla",
    al => "Albania",
    am => "Armenia",
    an => "Netherlands Antilles",
    ao => "Angola",
    aq => "Antarctica",
    ar => "Argentina",
    as => "American Samoa",
    at => "Austria",
    au => "Australia",
    aw => "Aruba",
    az => "Azerbaidjan",
    ba => "Bosnia-Herzegovina",
    bb => "Barbados",
    bd => "Bangladesh",
    be => "Belgium",
    bf => "Burkina Faso",
    bg => "Bulgaria",
    bh => "Bahrain",
    bi => "Burundi",
    bj => "Benin",
    bm => "Bermuda",
    bn => "Brunei Darussalam",
    bo => "Bolivia",
    br => "Brazil",
    bs => "Bahamas",
    bt => "Bhutan",
    bv => "Bouvet Island",
    bw => "Botswana",
    by => "Belarus",
    bz => "Belize",
    ca => "Canada",
    cc => "Cocos (Keeling) Islands",
    cf => "Central African Republic",
    cd => "Congo, The Democratic Republic of the",
    cg => "Congo",
    ch => "Switzerland",
    ci => "Ivory Coast (Cote D'Ivoire)",
    ck => "Cook Islands",
    cl => "Chile",
    cm => "Cameroon",
    cn => "China",
    co => "Colombia",
    cr => "Costa Rica",
    cs => "Former Czechoslovakia",
    cu => "Cuba",
    cv => "Cape Verde",
    cx => "Christmas Island",
    cy => "Cyprus",
    cz => "Czech Republic",
    de => "Germany",
    dj => "Djibouti",
    dk => "Denmark",
    dm => "Dominica",
    do => "Dominican Republic",
    dz => "Algeria",
    ec => "Ecuador",
    ee => "Estonia",
    eg => "Egypt",
    eh => "Western Sahara",
    er => "Eritrea",
    es => "Spain",
    et => "Ethiopia",
    fi => "Finland",
    fj => "Fiji",
    fk => "Falkland Islands",
    fm => "Micronesia",
    fo => "Faroe Islands",
    fr => "France",
    fx => "France (European Territory)",
    ga => "Gabon",
    gb => "Great Britain",
    gd => "Grenada",
    ge => "Georgia",
    gf => "French Guyana",
    gh => "Ghana",
    gi => "Gibraltar",
    gl => "Greenland",
    gm => "Gambia",
    gn => "Guinea",
    gp => "Guadeloupe (French)",
    gq => "Equatorial Guinea",
    gr => "Greece",
    gs => "S. Georgia & S. Sandwich Isls.",
    gt => "Guatemala",
    gu => "Guam (USA)",
    gw => "Guinea Bissau",
    gy => "Guyana",
    hk => "Hong Kong",
    hm => "Heard and McDonald Islands",
    hn => "Honduras",
    hr => "Croatia",
    ht => "Haiti",
    hu => "Hungary",
    id => "Indonesia",
    ie => "Ireland",
    il => "Israel",
    in => "India",
    io => "British Indian Ocean Territory",
    iq => "Iraq",
    ir => "Iran",
    is => "Iceland",
    it => "Italy",
    jm => "Jamaica",
    jo => "Jordan",
    jp => "Japan",
    ke => "Kenya",
    kg => "Kyrgyz Republic (Kyrgyzstan)",
    kh => "Cambodia, Kingdom of",
    ki => "Kiribati",
    km => "Comoros",
    kn => "Saint Kitts & Nevis Anguilla",
    kp => "North Korea",
    kr => "South Korea",
    kw => "Kuwait",
    ky => "Cayman Islands",
    kz => "Kazakhstan",
    la => "Laos",
    lb => "Lebanon",
    lc => "Saint Lucia",
    li => "Liechtenstein",
    lk => "Sri Lanka",
    lr => "Liberia",
    ls => "Lesotho",
    lt => "Lithuania",
    lu => "Luxembourg",
    lv => "Latvia",
    ly => "Libya",
    ma => "Morocco",
    mc => "Monaco",
    md => "Moldavia",
    mg => "Madagascar",
    mh => "Marshall Islands",
    mk => "Macedonia",
    ml => "Mali",
    mm => "Myanmar",
    mn => "Mongolia",
    mo => "Macau",
    mp => "Northern Mariana Islands",
    mq => "Martinique (French)",
    mr => "Mauritania",
    ms => "Montserrat",
    mt => "Malta",
    mu => "Mauritius",
    mv => "Maldives",
    mw => "Malawi",
    mx => "Mexico",
    my => "Malaysia",
    mz => "Mozambique",
    na => "Namibia",
    nc => "New Caledonia (French)",
    ne => "Niger",
    nf => "Norfolk Island",
    ng => "Nigeria",
    ni => "Nicaragua",
    nl => "Netherlands",
    no => "Norway",
    np => "Nepal",
    nr => "Nauru",
    nt => "Neutral Zone",
    nu => "Niue",
    nz => "New Zealand",
    om => "Oman",
    pa => "Panama",
    pe => "Peru",
    pf => "Polynesia (French)",
    pg => "Papua New Guinea",
    ph => "Philippines",
    pk => "Pakistan",
    pl => "Poland",
    pm => "Saint Pierre and Miquelon",
    pn => "Pitcairn Island",
    pr => "Puerto Rico",
    pt => "Portugal",
    pw => "Palau",
    py => "Paraguay",
    qa => "Qatar",
    re => "Reunion (French)",
    ro => "Romania",
    ru => "Russian Federation",
    rw => "Rwanda",
    sa => "Saudi Arabia",
    sb => "Solomon Islands",
    sc => "Seychelles",
    sd => "Sudan",
    se => "Sweden",
    sg => "Singapore",
    sh => "Saint Helena",
    si => "Slovenia",
    sj => "Svalbard and Jan Mayen Islands",
    sk => "Slovak Republic",
    sl => "Sierra Leone",
    sm => "San Marino",
    sn => "Senegal",
    so => "Somalia",
    sr => "Suriname",
    st => "Saint Tome (Sao Tome) and Principe",
    su => "Former USSR",
    sv => "El Salvador",
    sy => "Syria",
    sz => "Swaziland",
    tc => "Turks and Caicos Islands",
    td => "Chad",
    tf => "French Southern Territories",
    tg => "Togo",
    th => "Thailand",
    tj => "Tadjikistan",
    tk => "Tokelau",
    tm => "Turkmenistan",
    tn => "Tunisia",
    to => "Tonga",
    tp => "East Timor",
    tr => "Turkey",
    tt => "Trinidad and Tobago",
    tv => "Tuvalu",
    tw => "Taiwan",
    tz => "Tanzania",
    ua => "Ukraine",
    ug => "Uganda",
    uk => "United Kingdom",
    um => "USA Minor Outlying Islands",
    us => "United States",
    uy => "Uruguay",
    uz => "Uzbekistan",
    va => "Holy See (Vatican City State)",
    vc => "Saint Vincent & Grenadines",
    ve => "Venezuela",
    vg => "Virgin Islands (British)",
    vi => "Virgin Islands (USA)",
    vn => "Vietnam",
    vu => "Vanuatu",
    wf => "Wallis and Futuna Islands",
    ws => "Samoa",
    ye => "Yemen",
    yt => "Mayotte",
    yu => "Yugoslavia",
    za => "South Africa",
    zm => "Zambia",
    zr => "Zaire",
    zw => "Zimbabwe",
};

=back

=head1 DEPENDENCIES

None

=head1 AUTHOR

Kevin Hutchinson <kevin.hutchinson@legendum.com>

=head1 COPYRIGHT

Copyright (c) 2015 Legendum Ltd (UK)

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 3
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.
